services:
  - type: web
    name: radhin-portfolio-backend
    runtime: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://your-vercel-app.vercel.app
      - key: PORT
        value: 5000
